### ISSUE TITLE
Breaking application

### ISSUE THREAD

**Issue by jamesquox** [Steveiwonder/DataMasker#1]
When i run the app in android it break my phone! Now i need to reinstall windows! Please fix this, thanks.

**Comment by Steveiwonder** [comment]
Np, easy fix.

Uninstall your Sega mega drive operating system, upgrade the bios on your cat and connect the two together. Problem fixed.

On 21 February 2018 10:25:20 jamesquox <notifications@github.com> wrote:

When i run the app in android it break my phone! Now i need to reinstall windows! Please fix this, thanks.
