### ISSUE TITLE
Does support database integrity

### ISSUE THREAD

**Issue by malballah** [Steveiwonder/DataMasker#11]
Does DataMasker support database integrity like preserving the relations between tables based on the foreign key relations between tables?

**Comment by Steveiwonder** [comment]
Hey, as far as this library is concerned foreign keys don't cause any issues this only updates values and It won't update columns you don't tell it to. So if you have a table like so:

| UserId | UserTypeId | Username | .. etc 
     1               1          Steveiwonder

and UserTypeId is the foreign key, just ensure you don't add "UserTypeId" in the list of columns setting up the json config

**Comment by malballah** [comment]
Yes you are right, but sometimes emails can be foreign keys I know it is a bad practice.
The link of the schema of the configuration is not working, could you help with that? 
https://github.com/Steveiwonder/DataMasker/blob/master/src/DataMasker.Config.schema.json
Also how can I configure a social security number column?

**Comment by Steveiwonder** [comment]
In your case no, I'm sorry it's not intended to work with foreign keys columns.
I will fix that broken link soon np.
For your social security number you could look at using type "StringFormat" and  setting the stringFormatPattern to a SSN format

**Comment by malballah** [comment]
Yes, thank you
It is a good tool, and I did found the string format useful for any data type

**Comment by Steveiwonder** [comment]
You're welcome and thank you.
