### ISSUE TITLE
Other DBs?

### ISSUE THREAD

**Issue by DanteNahuel** [Steveiwonder/DataMasker#13]
Hi there
Amazing tool
I wanted to ask if it would be possible to add Oracle DB support and other DBs.
Thank you in advance.

**Comment by Steveiwonder** [comment]
Thank you! I'm busy with another project right now but I will look to extend support for oracle

**Comment by DanteNahuel** [comment]
Thank you for the reply.
This would mean adding a DataSource class, similar to the SQL but with Oracle connectors, correct?

**Comment by Steveiwonder** [comment]
Yep, it would be like that,

**Comment by DanteNahuel** [comment]
I'm gonna give it a try to see if I can make any progress, but if you can also look into it, it would be great.
I'm guessing I'll have to add a DataSource Class for oracle, a new DataSourceType, and add a switch case DataSourceType.OracleServer over DataSourceProvider

The thing that scrambles my head is the SqlMapper
Would something like it be also needed but for Oracle?

**Comment by Steveiwonder** [comment]
> Would something like it be also needed but for Oracle?

Yep

Closing this now due to inactivity, if you are successful feel free to crate a PR
