### ISSUE TITLE
Invalid object name

### ISSUE THREAD

**Issue by Jab555** [Steveiwonder/DataMasker#15]
In config file, 
"tables": [
	{
      "name": "User",  // the default schema is dbo, and this table is under dbo schema
.............................
        }
     ]
ABOVE CONFIG WORKS LIKE A CHARM.

When selecting table from different schema it will show invalid object name error.
Like if I had: 
"tables": [
	{
      "name": "schemaName.tableName",  
.............................
        }
     ]

It will show Invalid Object name. Can you help please?  How can I choose two different table from two different schema? Thanks

**Comment by Steveiwonder** [comment]
I will help you no problem. Please give me a few hours

**Comment by Jab555** [comment]
Hi there, thanks so much. So, is there any get around on using tables from different schema in the same config file?

**Comment by Steveiwonder** [comment]
You can now supply a "schema" option, see the documentation
