### ISSUE TITLE
[Question] How to substitute 300,000 names

### ISSUE THREAD

**Issue by Swellenator** [Steveiwonder/DataMasker#18]
Hi

How can I substitute 300,000 names? In the examples in the readme it has an entry for a name substitution, it's not really feasible to put 300,000 names in there, is there another way?

Thanks

**Comment by Steveiwonder** [comment]
Heya,

I assume you are referring to `valueMappings` ?

If so that is only there to basically exclude certain values from your database not for 300,000 exclusions.

Can I asked what you actually need?
