### ISSUE TITLE
DataMasker runs out of memory when processing large datasets

### ISSUE THREAD

**Issue by simonmckenzie** [Steveiwonder/DataMasker#20]
Hi,

Firstly, thanks for the great app - I've been finding it very useful.

I see that the app always runs as 32-bit - would it be possible for this to run at native bit-ness on 64-bit machines (i.e. by turning off "Prefer 32-bit")?

I have built the masker on my own machine with this flag turned off, and it worked fine, so it seems that it'd be a good improvement for the pre-built artifacts.

Thanks,

Simon

**Comment by Steveiwonder** [comment]
Hey, no problem, glad you find it useful and thanks for you contribution.
Your PR has been merged and is part of the following build: 
### AppVeyor
 https://ci.appveyor.com/project/Steveiwonder/datamasker/builds/26151573/artifacts
### Nuget:
https://www.nuget.org/packages/DataMasker/1.0.58
