### ISSUE TITLE
DataMasker still runs out of memory when processing ultra-large datasets

### ISSUE THREAD

**Issue by simonmckenzie** [Steveiwonder/DataMasker#23]
While the runner [now uses 64-bit memory addressing](https://github.com/Steveiwonder/DataMasker/issues/20), it can still run out of memory when processing large datasets. This is primarily due to the fact that all rows are retrieved into memory upfront.

The masker would require a lot less memory if it could "stream" the rows rather than loading them all - there would also need to be changes in the "grouping" code to use lazy enumeration.

**Comment by Steveiwonder** [comment]
Thank you! I wrote this for working with small databases and didn't really think anyone would actually use it. I will merge your PR.

**Comment by simonmckenzie** [comment]
No worries! Thank you for writing it - I've found it very useful.
