### ISSUE TITLE
Net Standard upgrade

### ISSUE THREAD

**Issue by rameshkanjinghat** [Steveiwonder/DataMasker#25]
Hello Steve,

I had a chance to use DataMasker with one of my projects recently. I must say it made my job a lot easier and efficient. I would like to thank you first.

I am using .Net Core 3.1 now. Do you have any plans to upgrade the project to net standard?

Thanks,
Ramesh

**Comment by Steveiwonder** [comment]
Hey, I will get around too it soonish, pretty busy with the recent holidays

**Comment by rameshkanjinghat** [comment]
Thank you Steve.

I hope you had a great holidays.

**Comment by Steveiwonder** [comment]
Hey @rameshkanjinghat
I know it's been a long time, but it can be tested in https://www.nuget.org/packages/DataMasker/2.0.14-alpha

I'm still to run my own tests.

**Comment by rameshkanjinghat** [comment]
Hi @Steveiwonder 

Sorry I took so long to respond. I will try it and let you know.

Thank you again.

**Comment by Steveiwonder** [comment]
I'm closing this off and masking https://www.nuget.org/packages/DataMasker/2.0.14-alpha as deprecated, there is another alpha build which has new features and also converts the project to netstandard2.1 and the runners to 3.1
https://www.nuget.org/packages/DataMasker/2.0.19-alpha
