### ISSUE TITLE
Use Select in JSON (Question)

### ISSUE THREAD

**Issue by louagej** [Steveiwonder/DataMasker#29]
Hi,

is it possible to add SQL statements in the config.json file in order to get an already anonimized value from another table?
for example:
```json
{
  "dataSource": {
    "type": "SqlServer",
    "config": {
       "name": "databasename",
       "userName": "databaseUserName",
       "password": "databasePassword",
       "server": "databaseServer"
    }   
  },  
  "tables": [    
    {
      "name": "Users",
      "schema": "dbo",
      "primaryKeyColumn": "UserId",
      "columns": [
        {
          "name": "FirstName",
          "type": "FirstName"
        }
      ]
    },
    {
      "name": "Tools",
      "schema": "dbo",
      "primaryKeyColumn": "ToolId",
      "columns": [
        {
          "name": "FirstName",
          "type": "calculated",
          "value": "SELECT FirstName FROM Users Where UserId = UserId"
        }
      ]
    }
  ]
}
```

**Comment by Steveiwonder** [comment]
Unfortunately not currently supported. I will look to put this in over the weekend

**Comment by Steveiwonder** [comment]
@louagej I've got a basic implementation of this working at the moment.

I've updated the docs, see the new data type "sql"

##### Sql
The current row is passed in as parameters and can be accessed using `@ColumnName`
```json
{
  "name":"CompanyName",
  "type": "Sql",
  "sqlValue": {
    "query":"SELECT Name FROM SampleCompanyNames WHERE UserId = @UserId",
    "valueHandling": "Null/KeepValue"
  }
}
```


https://github.com/Steveiwonder/DataMasker/tree/sql-support
You can get the source code out and compile it yourself or let me do some more testing and wait for a release, I'll do that shortly.

Please can you give feedback and let me know if you need any other features

**Comment by Steveiwonder** [comment]
@louagej you can see now download this in https://www.nuget.org/packages/DataMasker/2.0.19-alpha

I'll do some more testing on this over the next few days before it moves into the master branch
