### ISSUE TITLE
Release assets missing CLI executable

### ISSUE THREAD

**Issue by hc-jraymunt** [Steveiwonder/DataMasker#39]
When downloading the latest release asset "DataMasker.Runner.zip", I found the DataMasker.Runner release is missing the DataMasker.Runner.exe file. I ended up needing to download the source and building to get all of the needed files.

**Comment by Steveiwonder** [comment]
Hey, all sorted it was building for linux. Try this release https://github.com/Steveiwonder/DataMasker/releases/tag/2.0.56

**Comment by Steveiwonder** [comment]
Hey, all sorted it was building for linux. Try this release https://github.com/Steveiwonder/DataMasker/releases/tag/2.0.56

**Comment by hc-jraymunt** [comment]
Thanks!
