### ISSUE TITLE
Possible enhancements 

### ISSUE THREAD

**Issue by SilverZippo** [Steveiwonder/DataMasker#48]
Hi @Steveiwonder, 

Sorry to contact you this way, but I could not find your contact details in your profile, so .... 

This looks like a useful really tool which does many of the things I am trying to achieve, although not quite yet all of them. 

I have the use-case of an upgrade to a vendor supplied system: 

My workflow would be: 
1. Make a 'masked' copy of a live database on 'day 1' and keep a record of what the orginal and new values were - ideally in a different server/database to the 'subject' database.  
2. On 'day 2', take another fresh copy of the live database and apply the same exact changes to the records which were already there (using the previously stored values), and also 'mask' any new records which had appeared since the previous day (again adding to the record of what the orginal and new values had been).
3. Repeat from 2 until the upgrade is complete. 

It would also be useful to produce audit reports showing what was changed, and when, so it would be useful to have date/time/user for each time a 'before/after' record was added. 

Is this this kind of direction you have in mind ? 

Cheers, 

SilverZippo

**Comment by Steveiwonder** [comment]
Hey @SilverZippo - First off, no problem this is fine to reach out to me this way. I understand what you're after, however I don't currently have plans to modify the library in such a way, that feels like it's a little out of scope for what was intended.

**Comment by SilverZippo** [comment]
Thanks for getting back to me @Steveiwonder. I may take a look at extending it myself if I can find some time, in which case I'll contribute it back to you for your consideration.

**Comment by SilverZippo** [comment]
Thanks for getting back to me @Steveiwonder. I may take a look at extending it myself if I can find some time, in which case I'll contribute it back to you for your consideration.
