### ISSUE TITLE
Enforce Uniqueness on columns?

### ISSUE THREAD

**Issue by carl-berg** [Steveiwonder/DataMasker#7]
Is there any way to enforce uniqueness on a column? Some columns might for instance have a unique constraint. I assume you can get around this by assuming that most values will be unique and to implement a retry mechanism when exception is thrown, but it would be nice if the library could handle this...

**Comment by Steveiwonder** [comment]
This isn't currently supported but I'll look at adding it in as an option soon

**Comment by Steveiwonder** [comment]
Hey @carl-berg 
I kinda of made a bit of a guess as to what you were after, but I've added support for unique values per table/column

You can now add "unique": "true/false" to each column 

example: 
```
{
  "name": "EmailAddress",
  "type": "Bogus",
  "unique": true,
  "stringFormatPattern": "{{internet.email}}"
}
```

The documentation has been updated and you can see the changes in pull request https://github.com/Steveiwonder/DataMasker/pull/8

Available in nuget package: https://www.nuget.org/packages/DataMasker/1.0.47
